/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zkr_mysound_Utils */

#ifndef _Included_com_zkr_mysound_Utils
#define _Included_com_zkr_mysound_Utils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zkr_mysound_Utils_MODE_NORMAL
#define com_zkr_mysound_Utils_MODE_NORMAL 0L
#undef com_zkr_mysound_Utils_MODE_LUOLI
#define com_zkr_mysound_Utils_MODE_LUOLI 1L
#undef com_zkr_mysound_Utils_MODE_DASHU
#define com_zkr_mysound_Utils_MODE_DASHU 2L
#undef com_zkr_mysound_Utils_MODE_JINGSONG
#define com_zkr_mysound_Utils_MODE_JINGSONG 3L
#undef com_zkr_mysound_Utils_MODE_GAOGUAI
#define com_zkr_mysound_Utils_MODE_GAOGUAI 4L
#undef com_zkr_mysound_Utils_MODE_KONGLING
#define com_zkr_mysound_Utils_MODE_KONGLING 5L
/*
 * Class:     com_zkr_mysound_Utils
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_zkr_mysound_Utils_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
